name = "backend"
compatibility_date = "2024-08-25"

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGI5MWFiN2UtYzQ3OC00MTkwLWI5M2EtYTEzYzJkMDhiNjYwIiwidGVuYW50X2lkIjoiMDhhMGRmZmI3YWUyMDc3OTkwOGQwMjIyNGM5YjYyZjFlODUzMTc3NmY1ZjhlNDZmNjIxZjkwZjI5OTJiZTg0NyIsImludGVybmFsX3NlY3JldCI6IjQ0OGQ3ZmZhLTMwMWQtNDI5MC1iNzUwLWQwZmE2ZTAxOTFjNCJ9.2KtM6Vt4UW25zKYJ_3gC-5I-CxnRIPfRWqzi7amWFuo"
JWT_SECRET="pranav"
# [ai]
# binding = "AI"